import { AuditResult, ClaimResult } from "./types";

export function generateMarkdownReport(
  text: string,
  audit: AuditResult
): string {
  const date = new Date().toISOString().split("T")[0];
  const verdictEmoji = (v: ClaimResult["verdict"]) =>
    v === "verified" ? "✅" : v === "hallucinated" ? "❌" : "⚠️";

  let md = `# TruthTrace Audit Report
*Generated on ${date}*

---

## Trust Score: ${audit.trustScore}/100

| Metric | Count |
|--------|-------|
| Total Claims | ${audit.totalClaims} |
| ✅ Verified | ${audit.verifiedCount} |
| ⚠️ Unverified | ${audit.unverifiedCount} |
| ❌ Hallucinated | ${audit.hallucinatedCount} |

---

## Audited Document

\`\`\`
${text}
\`\`\`

---

## Claim-by-Claim Analysis

`;

  audit.claims.forEach((claim, i) => {
    md += `### ${i + 1}. ${verdictEmoji(claim.verdict)} ${claim.verdict.toUpperCase()} (${claim.confidence}% confidence)

**Claim:** ${claim.claim}

**Type:** ${claim.type}

**Reasoning:** ${claim.reasoning}

`;
    if (claim.supporting_quote) {
      md += `**Evidence Quote:**
> ${claim.supporting_quote}

`;
    }

    if (claim.sources.length > 0) {
      md += `**Sources:**\n`;
      claim.sources.forEach((src) => {
        md += `- [${src.title}](${src.url}) *(${src.source})*\n`;
      });
      md += "\n";
    }

    md += "---\n\n";
  });

  md += `*Report generated by [TruthTrace](https://truthtrace.vercel.app) — The AI Hallucination Auditor*\n`;

  return md;
}

export function generateJSONPayload(
  text: string,
  audit: AuditResult
): string {
  return JSON.stringify(
    {
      meta: {
        generated_at: new Date().toISOString(),
        tool: "TruthTrace v1.0",
      },
      input_text: text,
      audit,
    },
    null,
    2
  );
}

export function downloadFile(
  content: string,
  filename: string,
  mimeType: string
): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
