import { AuditResult } from "./types";

export function generateMarkdownReport(text: string, audit: AuditResult): string {
  const date = new Date().toISOString().split("T")[0];
  const verdictLabel = (v: string | null) =>
    v === "verified" ? "✅ VERIFIED" :
    v === "hallucinated" ? "❌ HALLUCINATED" :
    v === "unverified" ? "⚠️ UNVERIFIED" : "○ PENDING";

  let md = `# TruthTrace Audit Report
*Generated on ${date}*

---

## Trust Score: ${audit.trustScore}/100
*(Based on your decisions — ${audit.decidedCount} of ${audit.totalClaims} claims decided)*

| Metric | Count |
|--------|-------|
| Total Claims | ${audit.totalClaims} |
| ✅ Verified (you) | ${audit.verifiedCount} |
| ⚠️ Unverified (you) | ${audit.unverifiedCount} |
| ❌ Hallucinated (you) | ${audit.hallucinatedCount} |
| ○ Pending | ${audit.pendingCount} |

---

## Audited Document

\`\`\`
${text}
\`\`\`

---

## Claim-by-Claim Analysis

`;

  audit.claims.forEach((claim, i) => {
    md += `### ${i + 1}. ${verdictLabel(claim.userVerdict)} — Source Agreement: ${claim.sourceScore}%

**Claim:** ${claim.claim}

**Type:** ${claim.type}

**Sources:** ${claim.supportingCount} agree · ${claim.contradictingCount} disagree · ${claim.totalSources} total

**Evidence Summary:** ${claim.reasoning}

`;
    if (claim.supporting_quote) {
      md += `**Evidence Quote:**
> ${claim.supporting_quote}

`;
    }
    if (claim.sources.length > 0) {
      md += `**Sources:**\n`;
      claim.sources.forEach((src) => {
        md += `- [${src.title}](${src.url}) *(${src.source} · ${src.supports})*\n`;
      });
      md += "\n";
    }
    md += "---\n\n";
  });

  md += `*Report generated by [TruthTrace](https://truthtrace.vercel.app)*\n`;
  return md;
}

export function generateJSONPayload(text: string, audit: AuditResult): string {
  return JSON.stringify({ meta: { generated_at: new Date().toISOString(), tool: "TruthTrace v2.0" }, input_text: text, audit }, null, 2);
}

export function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url; a.download = filename; a.click();
  URL.revokeObjectURL(url);
}
